//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMgit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public short PositionId { get; set; }
        public string PositionName { get; set; }
        public string PositionDescription { get; set; }
        public string PayPeriod { get; set; }
        public decimal Payrate { get; set; }
    }
}
